### ISSUE TITLE
vvspy readme notice

### ISSUE THREAD

**Issue by zaanposni** [aschuma/vvs_direct_connect#1]
Hey @aschuma 

cooles Projekt!
Hättest du was dagegen, dass ich es auf dem Readme von [vvspy ](https://github.com/zaanposni/vvspy)erwähne?

**Comment by aschuma** [comment]
Hi Yannick @zaanposni 

gerne kannst Du das erwähnen. Die eigentliche Arbeit hast aber Du ja vorab geleistet. Insofern danke ich Dir für vvspy 🥇 

Grüße

**Comment by zaanposni** [comment]
Hab ich erledigt. 😄
Freut mich, dass dir vvspy geholfen hat. 👍
