### ISSUE TITLE
Homeassistant

### ISSUE THREAD

**Issue by vgr28** [aschuma/vvs_direct_connect#29]
Hallo, gibt es schon eine Möglichkeit für eine Homeassisnat Intgeration?

**Comment by aschuma** [comment]
Hallo vgr28

mit einer Homeassistant Integration kann ich leider nicht dienen.  

Ich betreibe selber nur eine Integration via 

`NodeRed (Cron Pull vvs_direct)  --- MQTT ---> Max7219`

Siehe https://github.com/aschuma/max7219-led-matrix-clock-mqtt-display

Das NodeRed Script kann ich bei Bedarf gerne zur Verfügung stellen

**Comment by aschuma** [comment]
Won't fix
